import { defineConfig, devices } from '@playwright/test';
import path from 'path';

/**
 * Playwright Config — AI Dual-Track Testing
 * Auto-generated by ai-dual-testing
 * Uses path.resolve to prevent relative path resolution bugs when passed via --config
 */
const e2eDir = path.resolve(__dirname, '../e2e');
const screenshotsDir = path.resolve(__dirname, '../reports/screenshots');
const htmlReportDir = path.resolve(__dirname, '../reports/playwright-report');

const port = process.env.PORT || '3000';
const baseURL = process.env.BASE_URL || `http://localhost:${port}`;
const devCommand = process.env.DEV_SERVER_CMD || 'npm run dev';

export default defineConfig({
  testDir: e2eDir,
  outputDir: screenshotsDir,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html', { outputFolder: htmlReportDir, open: 'never' }]],

  use: {
    baseURL,
    trace: 'on-first-retry',
    screenshot: 'on',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: {
    command: devCommand,
    url: baseURL,
    reuseExistingServer: true,
    timeout: 120 * 1000,
  },
});
